### ISSUE TITLE
Convert to inherit from  IComponent

### ISSUE THREAD

**Issue by StevenTCramer** [TimeWarpEngineering/timewarp-simple-icons#1]
Egil has good idea. 

Since these components doesn't have any state, you could change your base type to just implement IComponent and just create the render fragment by hand.

https://twitter.com/egilhansen/status/1554478682420527104?s=20

![image](https://user-images.githubusercontent.com/357219/191737777-cdacab03-4636-4120-b73c-ad28f4eecbd9.png)

**Comment by chan18** [comment]
assigning to my self will take a look.
